Category.create(name:'純米吟醸')
Category.create(name:'純米酒')
Category.create(name:'純米大吟醸')
Category.create(name:'スパークリング')
Category.create(name:'貴醸酒')
Category.create(name:'吟醸')
Category.create(name:'普通酒')
Category.create(name:'本醸造')
Category.create(name:'大吟醸')
Category.create(name:'吟醸酒')
Category.create(name:'特別本醸造')
Category.create(name:'特別純米酒')
Rice.create(name:'山田錦')
Rice.create(name:'五百万石')
Rice.create(name:'美山錦')
Rice.create(name:'雄町')
Rice.create(name:'秋田酒こまち')
Rice.create(name:'麹・山田錦、掛・ハナエチゼン')
Rice.create(name:'亀の尾（山形県産）')
Rice.create(name:'夢ささら')
Rice.create(name:'美郷錦')
Rice.create(name:'総の舞（千葉県産）')
Rice.create(name:'山田錦（兵庫県三木市吉川町特A地区産）')
Rice.create(name:'出羽燦々')
Rice.create(name:'八反錦')
Rice.create(name:'愛山')
Rice.create(name:'夢の香')
Rice.create(name:'吟吹雪')
Rice.create(name:'ひとごこち、美山錦')
Rice.create(name:'金紋錦')
Rice.create(name:'蔵の華')
Rice.create(name:'山田穂')
Rice.create(name:'山田錦、イセヒカリ')
Rice.create(name:'日本晴、山田錦')
Rice.create(name:'東北酒218号')
Rice.create(name:'美郷錦、酒こまち')
Rice.create(name:'酒こまち')
Rice.create(name:'吟のさと')
Rice.create(name:'にこまる')
Rice.create(name:'石川門')
Rice.create(name:'コシヒカリ')
Rice.create(name:'吟風')
Rice.create(name:'あさひの夢')
Rice.create(name:'彗星')
Rice.create(name:'美山錦、ひとごこち')
Rice.create(name:'越淡麗')
Rice.create(name:'亀の尾')
Rice.create(name:'改良信交')
Rice.create(name:'ハナエチゼン')
Rice.create(name:'さかほまれ')
Rice.create(name:'山田錦、夢一献')
Rice.create(name:'秋田酒120号')
Rice.create(name:'常陸錦')
Rice.create(name:'ふさこがね')
Kuramoto.create(name:'林本店')
Kuramoto.create(name:'油長酒造')
Kuramoto.create(name:'山の壽酒造')
Kuramoto.create(name:'大澤酒造')
Kuramoto.create(name:'赤武酒造')
Kuramoto.create(name:'来福酒造')
Kuramoto.create(name:'鶴乃江酒造')
Kuramoto.create(name:'龍神酒造')
Kuramoto.create(name:'黒龍酒造')
Kuramoto.create(name:'花の香酒造')
Kuramoto.create(name:'酒井酒造')
Kuramoto.create(name:'鍋店')
Kuramoto.create(name:'立山酒造')
Kuramoto.create(name:'松崎酒造店')
Kuramoto.create(name:'鈴木酒造店長井蔵')
Kuramoto.create(name:'車多酒造')
Kuramoto.create(name:'藤平酒造')
Kuramoto.create(name:'宮坂醸造')
Kuramoto.create(name:'所酒造')
Kuramoto.create(name:'鈴木酒造店')
Kuramoto.create(name:'水戸部酒造')
Kuramoto.create(name:'吉久保酒造')
Kuramoto.create(name:'大沼酒造店')
Kuramoto.create(name:'相原酒造')
Kuramoto.create(name:'竹鶴酒造')
Kuramoto.create(name:'木戸泉酒造')
Kuramoto.create(name:'金光酒造')
Kuramoto.create(name:'旭酒造')
Kuramoto.create(name:'栗林酒造店')
Kuramoto.create(name:'藤岡酒造')
Kuramoto.create(name:'亀萬酒造')
Kuramoto.create(name:'冨田酒造')
Kuramoto.create(name:'重家酒造')
Kuramoto.create(name:'惣誉酒造')
Kuramoto.create(name:'白菊酒造')
Kuramoto.create(name:'農口尚彦研究所')
Kuramoto.create(name:'富美菊酒造')
Kuramoto.create(name:'麓井酒造')
Kuramoto.create(name:'濱川商店')
Kuramoto.create(name:'アリサワ')
Kuramoto.create(name:'福禄寿酒造')
Kuramoto.create(name:'萬乗醸造')
Kuramoto.create(name:'東灘醸造')
Kuramoto.create(name:'八戸酒造')
Kuramoto.create(name:'平和酒造')
Kuramoto.create(name:'麒麟山酒造')
Kuramoto.create(name:'小林酒造株')
Kuramoto.create(name:'上原酒造')
Kuramoto.create(name:'古伊万里酒造')
Kuramoto.create(name:'大嶺酒造')
Kuramoto.create(name:'永井酒造')
Kuramoto.create(name:'宮尾酒造')
Kuramoto.create(name:'曙酒造')
Kuramoto.create(name:'山本')
Kuramoto.create(name:'元坂酒造')
Kuramoto.create(name:'青木酒造')
Kuramoto.create(name:'平孝酒造')
Kuramoto.create(name:'加茂錦酒造')
Kuramoto.create(name:'永山本家酒造場')
Kuramoto.create(name:'小林酒造')
Kuramoto.create(name:'仙頭酒造場')
Kuramoto.create(name:'菊の里酒造')
Kuramoto.create(name:'大木代吉本店')
Kuramoto.create(name:'八海醸造')
Kuramoto.create(name:'中島醸造')
Kuramoto.create(name:'高嶋酒造')
Kuramoto.create(name:'墨廼江酒造')
Kuramoto.create(name:'泉橋酒造')
Kuramoto.create(name:'畑酒造')
Kuramoto.create(name:'菊姫')
Kuramoto.create(name:'桝田酒造店')
Kuramoto.create(name:'宝剣酒造')
Kuramoto.create(name:'三宅彦右衛門酒造')
Kuramoto.create(name:'本田商店')
Kuramoto.create(name:'熊澤酒造')
Kuramoto.create(name:'出羽桜酒造')
Kuramoto.create(name:'毛利酒造')
Kuramoto.create(name:'山陽盃酒造')
Kuramoto.create(name:'秋田清酒')
Kuramoto.create(name:'高橋庄作酒造店')
Kuramoto.create(name:'山本酒造店')
Kuramoto.create(name:'吉田酒造（白龍）')
Kuramoto.create(name:'神沢川酒造場')
Kuramoto.create(name:'酔鯨酒造')
Kuramoto.create(name:'富士酒造')
Kuramoto.create(name:'新藤酒造店')
Kuramoto.create(name:'諸橋酒造')
Kuramoto.create(name:'阿部勘酒造店')
Kuramoto.create(name:'石鎚酒造')
Kuramoto.create(name:'松瀬酒造')
Kuramoto.create(name:'阿部酒造')
Kuramoto.create(name:'新澤醸造店')
Kuramoto.create(name:'萩野酒造')
Kuramoto.create(name:'仁井田本家')
Kuramoto.create(name:'福田酒造')
Kuramoto.create(name:'月の井酒造店')
Kuramoto.create(name:'喜多酒造')
Kuramoto.create(name:'今田酒造本店')
Kuramoto.create(name:'マスカガミ')
Kuramoto.create(name:'せんきん')
Kuramoto.create(name:'山口酒造場')
Kuramoto.create(name:'鳩正宗')
Kuramoto.create(name:'みいの寿')
Kuramoto.create(name:'寺田本家')
Kuramoto.create(name:'阿桜酒造')
Kuramoto.create(name:'一ノ蔵')
Kuramoto.create(name:'佐浦')
Kuramoto.create(name:'小嶋総本店')
Kuramoto.create(name:'渡辺酒造店')
Kuramoto.create(name:'松本酒造')
Kuramoto.create(name:'WAKAZE')
Kuramoto.create(name:'中国醸造')
Kuramoto.create(name:'平考酒造')
Kuramoto.create(name:'秋田醸造')
Kuramoto.create(name:'石本酒造')
Kuramoto.create(name:'旭鶴')
Kuramoto.create(name:'九重雑賀')
Kuramoto.create(name:'八木酒造部')
Kuramoto.create(name:'丸本酒造')
Kuramoto.create(name:'二世古酒造')
Kuramoto.create(name:'吉田酒造')
Kuramoto.create(name:'辻本店')
Kuramoto.create(name:'花泉酒造')
Kuramoto.create(name:'早川酒造')
Kuramoto.create(name:'吉村秀雄商店')
Kuramoto.create(name:'山忠本家酒造')
Kuramoto.create(name:'土田酒造')
Kuramoto.create(name:'奥羽自慢')
Kuramoto.create(name:'土屋酒造店')
Kuramoto.create(name:'吉田酒造店')
Kuramoto.create(name:'NEXT FIVE')
Kuramoto.create(name:'御祖酒造')
Kuramoto.create(name:'皇国晴酒造')
Kuramoto.create(name:'五町田酒造')
Kuramoto.create(name:'玉泉堂酒造')
Kuramoto.create(name:'宮泉銘醸')
Kuramoto.create(name:'亀の井酒造')
Kuramoto.create(name:'岩瀬酒造')
Kuramoto.create(name:'今西酒造')
Kuramoto.create(name:'若波酒造')
Kuramoto.create(name:'萱島酒造')
Kuramoto.create(name:'釜屋')
Kuramoto.create(name:'会津酒造')
Kuramoto.create(name:'加藤吉平商店')
Kuramoto.create(name:'天山酒造')
Kuramoto.create(name:'加藤嘉八郎酒造')
Kuramoto.create(name:'南部美人')
Kuramoto.create(name:'菊姫合資会社')
Kuramoto.create(name:'晒名酒造')
Kuramoto.create(name:'宝酒造')
Kuramoto.create(name:'鹿野酒造')
Kuramoto.create(name:'酒田酒造')
Kuramoto.create(name:'柴田酒造場')
Kuramoto.create(name:'楯の川酒造')
Kuramoto.create(name:'初亀醸造')
Kuramoto.create(name:'瀧自慢酒造')
Kuramoto.create(name:'澄川酒造場')
Kuramoto.create(name:'無手無冠')
Kuramoto.create(name:'小松酒造場')
Kuramoto.create(name:'国権酒造')
Kuramoto.create(name:'高知酒造')
Kuramoto.create(name:'三千盛')
Kuramoto.create(name:'司牡丹酒造')
Kuramoto.create(name:'山和酒造店')
Kuramoto.create(name:'西出酒造')
Kuramoto.create(name:'神亀酒造')
Kuramoto.create(name:'酔仙酒造')
Kuramoto.create(name:'水戸部酒造、楯の川酒造、小嶋総本店、男山酒造')
Kuramoto.create(name:'青島酒造')
Kuramoto.create(name:'美吉野醸造')
Kuramoto.create(name:'髙橋庄作酒造店')
Kuramoto.create(name:'井賀屋酒造場')
Kuramoto.create(name:'上川大雪酒造')
Kuramoto.create(name:'大七酒造')
Kuramoto.create(name:'西田酒造店')
Kuramoto.create(name:'小澤酒造')
Kuramoto.create(name:'松乃井酒造場')
Kuramoto.create(name:'夢心酒造')
Kuramoto.create(name:'西酒造')
Kuramoto.create(name:'福光屋')
Kuramoto.create(name:'地域商社やまぐち株式会社')
Kuramoto.create(name:'飛良泉本舗')
Kuramoto.create(name:'南酒造場')
Kuramoto.create(name:'白糸酒造')
Kuramoto.create(name:'仙台伊澤家勝山酒造')
Kuramoto.create(name:'千田酒造')
Kuramoto.create(name:'浅舞酒造')
Kuramoto.create(name:'飯沼本家')
Kuramoto.create(name:'梅一輪酒造')
Kuramoto.create(name:'朝日酒造')
Kuramoto.create(name:'三和酒類')
Kuramoto.create(name:'山梨銘醸')
Kuramoto.create(name:'男山')
Kuramoto.create(name:'長龍酒造')
StorageMethod.create(name:'原酒')
StorageMethod.create(name:'生酒')
StorageMethod.create(name:'生貯蔵酒')
StorageMethod.create(name:'生詰酒')
StorageMethod.create(name:'荒走り')
StorageMethod.create(name:'中取り')
StorageMethod.create(name:'にごり酒')
StorageMethod.create(name:'長期貯蔵酒')
StorageMethod.create(name:'新種')
StorageMethod.create(name:'ひやおろし')
StorageMethod.create(name:'生酛')
StorageMethod.create(name:'樽酒')
StorageMethod.create(name:'貴醸酒')
StorageMethod.create(name:'凍結酒')
Item.create(name:'百十郎 純米吟醸 G-mid(ジーミッド) 720ml', price:'1350', info:'岐阜 G酵母(※)を使用した日本酒。爽やかな吟醸香。口に含むとジューシーなお米の味わいが広がります。クリアでキレイな酒質が特徴。日々の食のシーンに彩を添えてくれるお酒です。※G酵母とはG酵母は9号系派生株。華やかな吟醸香と高い発酵力が特徴で、主に吟醸酒･純米酒等の製造に使われています。■日本酒度：+2~+4 ■酸度：1.2~1.4', size:'720ml', alcohol_degree:'15度', category_id:'1', rice_id:'1', storage_method_id:'1',kuramoto_id:'1',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'鷹長 菩提もと 甕熟成 6年古酒 720ml', price:'2500', info:'「菩提モト造り」とは、室町時代（1400年代）に奈良菩提山正暦寺で始まった醸造法で、製造工程で生米を使用するのが特徴です。正暦寺・寺領の米と水を使い、境内より分離した「正暦寺乳酸菌」「正暦寺酵母」の働きにより酒母を造り、これに近代醸造法を融合させた、奈良県独自の地域特性のある濃厚旨口の純米酒です。この商品はさらに瓷で6年間熟成させてある特別なお酒。', size:'720ml', alcohol_degree:'15度', category_id:'2', rice_id:'1', storage_method_id:'1',kuramoto_id:'2',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'山の壽 特別純米酒 1.8L', price:'2800', info:'山田錦の膨らみのある旨みと香りが口中で広がります。 若干のほろ苦さが、甘さを引き締め、全体的にバランスのとれた 飲み応えと飲みやすさを兼ね備えた酒質です。', size:'1.8L', alcohol_degree:'16度', category_id:'2', rice_id:'1', storage_method_id:'1',kuramoto_id:'3',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'明鏡止水 垂氷 甕口 純米 山田錦 無濾過原酒 720ml', price:'1300', info:'垂氷（つらら）ができる厳寒期に醸されたお酒です。 山田錦の旨みとしっかりしたキレをそろえた質感をお楽しみいただけます。 しぼりたての生原酒で、僅かにオリが絡んでおります。■日本酒度：+5 ■酸度：1.6', size:'720ml', alcohol_degree:'18～19度', category_id:'2', rice_id:'1', storage_method_id:'1',kuramoto_id:'4',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'百十郎 純米吟醸 G-mid(ジーミッド) 1.8L', price:'2600', info:'岐阜 G酵母(※)を使用した日本酒。爽やかな吟醸香。口に含むとジューシーなお米の味わいが広がります。クリアでキレイな酒質が特徴。日々の食のシーンに彩を添えてくれるお酒です。※G酵母とはG酵母は9号系派生株。華やかな吟醸香と高い発酵力が特徴で、主に吟醸酒･純米酒等の製造に使われています。■日本酒度：+2~+4 ■酸度：1.2~1.4', size:'1.8L', alcohol_degree:'15度', category_id:'1', rice_id:'1', storage_method_id:'1',kuramoto_id:'1',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'赤武 AKABU 純米吟醸 山田錦 720ml', price:'1900', info:'赤武シリーズで初となる山田錦を使用したお酒です。フルーティな吟醸香。口に含むと豊かで雑味が少なく澄んだお米の旨味が広がります。優しい甘味と程よい酸味、そして山田錦のふくよかさを感じられる1本です。■日本酒度：±0 ■酸度：1.4', size:'720ml', alcohol_degree:'15度', category_id:'1', rice_id:'1', storage_method_id:'1',kuramoto_id:'5',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'明鏡止水 垂氷 甕口 純米 山田錦 無濾過原酒 1.8L', price:'2600', info:'垂氷（つらら）ができる厳寒期に醸されています。 米の旨味とキレを兼ね備えた純米酒です。 搾りたてそのままの無濾過生原酒のため、パワフルで呑み応えのある特別限定品です。■日本酒度：+6 ■酸度：2.0', size:'1.8L', alcohol_degree:'18～19度', category_id:'2', rice_id:'1', storage_method_id:'1',kuramoto_id:'4',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'赤武 AKABU 純米吟醸 山田錦 1.8L', price:'3800', info:'赤武シリーズで初となる山田錦を使用したお酒です。フルーティな吟醸香。口に含むと豊かで雑味が少なく澄んだお米の旨味が広がります。優しい甘味と程よい酸味、そして山田錦のふくよかさを感じられる1本です。■日本酒度：±0 ■酸度：1.4', size:'1.8L', alcohol_degree:'15度', category_id:'1', rice_id:'1', storage_method_id:'1',kuramoto_id:'5',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'来福 純米吟醸 なでしこの花酵母 1.8L', price:'3000', info:'イチゴの花から抽出した酵母で醸した純米吟醸酒。 ほのかなベリー系の香りがあり、夏のイチゴのような爽やかな酸味と優しい甘さを感じます。', size:'1.8L', alcohol_degree:'16度', category_id:'1', rice_id:'1', storage_method_id:'1',kuramoto_id:'6',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'会津中将 特別純米 うすにごり生 720ml', price:'1500', info:'僅かなガス感と瑞々しい旨み、すっきりとした飲み口です。 オリが絡んだほろ苦さが上品なボディとフレッシュ感を 醸しだしています。■日本酒度：+2 ■酸度：1.5', size:'720ml', alcohol_degree:'16度', category_id:'2', rice_id:'1', storage_method_id:'1',kuramoto_id:'7',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'来福 超精米八% 純米大吟醸 720ml箱入り', price:'11111', info:'茨城県の酒造好適米「ひたち錦」米を100％使用し、なんと8％まで磨き上げた贅沢な純米大吟醸酒。最高品質の日本酒を目指す来福酒造の渾身の一本！SAKE COMPETITION2016のSuper Premium 部門において第1位を獲得致しました。', size:'720ml箱入り', alcohol_degree:'16度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'6',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'来福 スパークリング ～Sparkling Raifuku～ 750ml', price:'1750', info:'口の中で広がる炭酸ガスのシュワシュワ感と、のどごしの爽やかなお酒です。糖類、酸味料は一切使用せず、お米本来の優しい甘味があります。見た目にも迫力あるシャンパンボトルを使用し、本格的なデザインとなっています。※吹きこぼれる場合がありますので、充分に冷やしてから、ゆっくり開栓して下さい。', size:'750ml', alcohol_degree:'12度', category_id:'4', rice_id:'1', storage_method_id:'1',kuramoto_id:'6',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'山の壽 特別純米酒 720ml', price:'1400', info:'山田錦の膨らみのある旨みと香りが口中で広がります。 若干のほろ苦さが、甘さを引き締め、全体的にバランスのとれた 飲み応えと飲みやすさを兼ね備えた酒質です。', size:'720ml', alcohol_degree:'16度', category_id:'2', rice_id:'1', storage_method_id:'1',kuramoto_id:'3',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'来福 MELLOW 貴醸酒 1.8L', price:'3100', info:'日本酒を仕込む際の仕込み水の一部に純米酒を使用して醸した貴醸酒です。甘味と酸味の良いデザート感覚で飲めるお酒です。', size:'1.8L', alcohol_degree:'15度', category_id:'5', rice_id:'1', storage_method_id:'1',kuramoto_id:'6',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'会津中将 特別純米 うすにごり生 1.8L', price:'2800', info:'僅かなガス感と瑞々しい旨み、すっきりとした飲み口です。 オリが絡んだほろ苦さが上品なボディとフレッシュ感を 醸しだしています。■日本酒度：+2 ■酸度：1.5', size:'1.8L', alcohol_degree:'16度', category_id:'2', rice_id:'1', storage_method_id:'1',kuramoto_id:'7',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'龍神 バックステージパス 隠し酒 1.8L', price:'2000', info:'白い花を想わせる穏やかで上品な香りと柔らかな酸、 心地良い甘みが潔くフェードアウトする。コストパフォーマンスの高い吟醸酒です。■日本酒度：-2 ■酸度：1.3', size:'1.8L', alcohol_degree:'15度', category_id:'6', rice_id:'1', storage_method_id:'1',kuramoto_id:'8',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'黒龍 吟醸 いっちょらい 1.8L', price:'2450', info:'「いっちょらい」とは福井の方言で「一張羅」のこと。その名にふさわしい香りと味が瓶の中に大切に詰められております。 メロンを思わせる香り、後に引かない程よい旨味が絶妙なバランス。ぜひ飲んでいただきたい一本です。', size:'1.8L', alcohol_degree:'15度', category_id:'6', rice_id:'2', storage_method_id:'1',kuramoto_id:'9',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'龍神 純米大吟醸 瓶燗火入 720ml', price:'1620', info:'四合瓶専用としてつくられた純米大吟醸酒。大人の穏やかな味わいの火入れ酒をお求めの方にぴったりな仕上がりになっています。洋梨を想わせる熟した果実香に、ビビットな酸と官能的な甘味のバランスが心地よい味わい。食中に映えるスタンダードな1本です。', size:'720ml', alcohol_degree:'16度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'8',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'黒龍 吟醸 いっちょらい 720ml', price:'1150', info:'「いっちょらい」とは福井の方言で「一張羅」のこと。その名にふさわしい香りと味が瓶の中に大切に詰められております。', size:'720ml', alcohol_degree:'15度', category_id:'6', rice_id:'2', storage_method_id:'1',kuramoto_id:'9',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'尾瀬の雪どけ 純米大吟醸 試験醸造酒 PROTOTYPE 愛山 1.8L', price:'3180', info:'【蔵元より】ハロウィンで投入した「白麹」の残りを一部用いて、麹米山田錦・掛米愛山の豪華な組み合わせを演出いたしました。白ワインを想わせる高級な芳香と、甘味を〆る独自の酸が特徴です。', size:'1.8L', alcohol_degree:'15度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'8',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'花の香 純米大吟醸 桜花 火入 1.8L', price:'2727', info:'日本一の酒米と言われる「山田錦」を、50％まで丁寧に磨いて醸した純米大吟醸。澄んだ味わいと上品な香りが絶妙。全量地元産のお米で最高の酒を造るという夢に向かって修行した、若い蔵人と造り上げたお酒です。', size:'1.8L', alcohol_degree:'16度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'10',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'龍神 純米大吟醸 Opening Act（オープニングアクト） 生 1.8L', price:'2900', info:'龍神酒造さん30BYの新酒です。メロンや洋梨を思わせる穏やかな吟醸香があり、 柔らかな酸とお米の甘みが特徴的な味わいです。', size:'1.8L', alcohol_degree:'15度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'8',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'花の香 純米大吟醸 桜花 火入 720ml', price:'1363', info:'日本一の酒米と言われる「山田錦」を、50％まで丁寧に磨いて醸した純米大吟醸。澄んだ味わいと上品な香りが絶妙。全量地元産のお米で最高の酒を造るという夢に向かって修行した、若い蔵人と造り上げたお酒です。', size:'720ml', alcohol_degree:'16度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'10',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'尾瀬の雪どけ 純米大吟醸 彗星30% 1.8L', price:'3130', info:'平成の30年間にちなんで、北海道産の酒造好適米、彗星を30％まで磨いて低温で30日間醸されたお酒です。 グレープフルーツのようなみずみずしい果実香に、ほのかな乳酸系の香りを纏ったお米の旨味を綺麗な酸が切ってくれる印象。磨き30％と高精白ならではの透明感がある味わいが特徴的です。', size:'1.8L', alcohol_degree:'15度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'8',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'五橋 五（five） 純米大吟醸 ピンク 生原酒 1.8L', price:'3700', info:'ロゴカラーのピンクにふさわしい、華やかで上品な吟醸香。今年は華やかさに加え、搾りたてのフレッシュさと旨味のジューシーさがアップしています。大吟醸ならではの繊細な口当たり、そして木桶仕込み+生もとブレンドによる、柔らかさのある酒質になっています。■日本酒度：-5 ■酸度：1.7', size:'1.8L', alcohol_degree:'16度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'11',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'尾瀬の雪どけ 純米大吟醸 北都七星 1.8L', price:'2760', info:'【蔵元より】北の都、旭川近郊の豊かな大地に育まれた、食味の良い一般米「ななつぼし」を掛米に使用し、名前に因んだ7号酵母で醸しました。 ほのかな米の甘さに北海道の初夏の爽やかな気候を想わせるあっさりとした味わいに7号酵母の綺麗な酸が載った純米大吟醸酒です。', size:'1.8L', alcohol_degree:'15度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'8',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'五橋 五（five） 純米大吟醸 ピンク 生原酒 720ml', price:'1850', info:'ロゴカラーのピンクにふさわしい、華やかで上品な吟醸香。今年は華やかさに加え、搾りたてのフレッシュさと旨味のジューシーさがアップしています。大吟醸ならではの繊細な口当たり、そして木桶仕込み+生もとブレンドによる、柔らかさのある酒質になっています。■日本酒度：-5 ■酸度：1.7', size:'720ml', alcohol_degree:'16度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'11',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'不動 純米大吟醸 山田錦35% 吊るししぼり 1.8L箱入り', price:'8333', info:'兵庫県で最も良質な酒米をつくるA地区で栽培された山田錦を35％精米し、吊るししぼりで上槽。 低温でじっくり熟成させることで、優しい口当たりでしっかりとした米の旨味と芳醇な香りが幾重にも調和して、最上の味わいを醸し出しています。（※）吊るししぼりとは？お酒を搾る際に圧力を全くかけず、吊るした酒袋から重力のみでお酒を集める事。 ■日本酒度：+1.5 ■酸度：1.4', size:'1.8L箱入り', alcohol_degree:'16.2度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'12',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'立山 特別純米酒 愛山 酒中仙 1.8L', price:'2887', info:'【蔵元より】希少価値の高い酒造好適米「愛山」を全量用いて醸した特別純米酒。ほのかで柔らかい芳香。味わいのある適度な酸と豊かな旨み。冷酒からぬる燗まで幅広くお愉しみいただけます。', size:'1.8L', alcohol_degree:'15～16度', category_id:'2', rice_id:'1', storage_method_id:'1',kuramoto_id:'13',prefecture_id:'1' , delivery_method:'クール便')
Item.create(name:'不動 純米大吟醸 山田錦35% 吊るししぼり 720ml箱入り', price:'4166', info:'兵庫県で最も良質な酒米をつくる特A地区で栽培された山田錦を35％精米し、吊るししぼりで上槽。 低温でじっくり熟成させることで、優しい口当たりでしっかりとした米の旨味と芳醇な香りが幾重にも調和して、最上の味わいを醸し出しています。（※）吊るししぼりとは？お酒を搾る際に圧力を全くかけず、吊るした酒袋から重力のみでお酒を集める事。 ■日本酒度：+1.5 ■酸度：1.4', size:'720ml箱入り', alcohol_degree:'16.2度', category_id:'3', rice_id:'1', storage_method_id:'1',kuramoto_id:'12',prefecture_id:'1' , delivery_method:'クール便')